/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TokenCreateIndexImport } from './routes/token-create/index'
import { Route as SendIndexImport } from './routes/send/index'
import { Route as ReceiveIndexImport } from './routes/receive/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as CurrencyDisplayIndexImport } from './routes/currency-display/index'
import { Route as NftsMyNftsImport } from './routes/nfts/my-nfts'
import { Route as NftsCreateImport } from './routes/nfts/create'
import { Route as BalanceIdImport } from './routes/balance/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TokenCreateIndexRoute = TokenCreateIndexImport.update({
  id: '/token-create/',
  path: '/token-create/',
  getParentRoute: () => rootRoute,
} as any)

const SendIndexRoute = SendIndexImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => rootRoute,
} as any)

const ReceiveIndexRoute = ReceiveIndexImport.update({
  id: '/receive/',
  path: '/receive/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const CurrencyDisplayIndexRoute = CurrencyDisplayIndexImport.update({
  id: '/currency-display/',
  path: '/currency-display/',
  getParentRoute: () => rootRoute,
} as any)

const NftsMyNftsRoute = NftsMyNftsImport.update({
  id: '/nfts/my-nfts',
  path: '/nfts/my-nfts',
  getParentRoute: () => rootRoute,
} as any)

const NftsCreateRoute = NftsCreateImport.update({
  id: '/nfts/create',
  path: '/nfts/create',
  getParentRoute: () => rootRoute,
} as any)

const BalanceIdRoute = BalanceIdImport.update({
  id: '/balance/$id',
  path: '/balance/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/balance/$id': {
      id: '/balance/$id'
      path: '/balance/$id'
      fullPath: '/balance/$id'
      preLoaderRoute: typeof BalanceIdImport
      parentRoute: typeof rootRoute
    }
    '/nfts/create': {
      id: '/nfts/create'
      path: '/nfts/create'
      fullPath: '/nfts/create'
      preLoaderRoute: typeof NftsCreateImport
      parentRoute: typeof rootRoute
    }
    '/nfts/my-nfts': {
      id: '/nfts/my-nfts'
      path: '/nfts/my-nfts'
      fullPath: '/nfts/my-nfts'
      preLoaderRoute: typeof NftsMyNftsImport
      parentRoute: typeof rootRoute
    }
    '/currency-display/': {
      id: '/currency-display/'
      path: '/currency-display'
      fullPath: '/currency-display'
      preLoaderRoute: typeof CurrencyDisplayIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/receive/': {
      id: '/receive/'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveIndexImport
      parentRoute: typeof rootRoute
    }
    '/send/': {
      id: '/send/'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendIndexImport
      parentRoute: typeof rootRoute
    }
    '/token-create/': {
      id: '/token-create/'
      path: '/token-create'
      fullPath: '/token-create'
      preLoaderRoute: typeof TokenCreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance/$id': typeof BalanceIdRoute
  '/nfts/create': typeof NftsCreateRoute
  '/nfts/my-nfts': typeof NftsMyNftsRoute
  '/currency-display': typeof CurrencyDisplayIndexRoute
  '/history': typeof HistoryIndexRoute
  '/receive': typeof ReceiveIndexRoute
  '/send': typeof SendIndexRoute
  '/token-create': typeof TokenCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance/$id': typeof BalanceIdRoute
  '/nfts/create': typeof NftsCreateRoute
  '/nfts/my-nfts': typeof NftsMyNftsRoute
  '/currency-display': typeof CurrencyDisplayIndexRoute
  '/history': typeof HistoryIndexRoute
  '/receive': typeof ReceiveIndexRoute
  '/send': typeof SendIndexRoute
  '/token-create': typeof TokenCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/balance/$id': typeof BalanceIdRoute
  '/nfts/create': typeof NftsCreateRoute
  '/nfts/my-nfts': typeof NftsMyNftsRoute
  '/currency-display/': typeof CurrencyDisplayIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/receive/': typeof ReceiveIndexRoute
  '/send/': typeof SendIndexRoute
  '/token-create/': typeof TokenCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance/$id'
    | '/nfts/create'
    | '/nfts/my-nfts'
    | '/currency-display'
    | '/history'
    | '/receive'
    | '/send'
    | '/token-create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance/$id'
    | '/nfts/create'
    | '/nfts/my-nfts'
    | '/currency-display'
    | '/history'
    | '/receive'
    | '/send'
    | '/token-create'
  id:
    | '__root__'
    | '/'
    | '/balance/$id'
    | '/nfts/create'
    | '/nfts/my-nfts'
    | '/currency-display/'
    | '/history/'
    | '/receive/'
    | '/send/'
    | '/token-create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceIdRoute: typeof BalanceIdRoute
  NftsCreateRoute: typeof NftsCreateRoute
  NftsMyNftsRoute: typeof NftsMyNftsRoute
  CurrencyDisplayIndexRoute: typeof CurrencyDisplayIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ReceiveIndexRoute: typeof ReceiveIndexRoute
  SendIndexRoute: typeof SendIndexRoute
  TokenCreateIndexRoute: typeof TokenCreateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceIdRoute: BalanceIdRoute,
  NftsCreateRoute: NftsCreateRoute,
  NftsMyNftsRoute: NftsMyNftsRoute,
  CurrencyDisplayIndexRoute: CurrencyDisplayIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ReceiveIndexRoute: ReceiveIndexRoute,
  SendIndexRoute: SendIndexRoute,
  TokenCreateIndexRoute: TokenCreateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/balance/$id",
        "/nfts/create",
        "/nfts/my-nfts",
        "/currency-display/",
        "/history/",
        "/receive/",
        "/send/",
        "/token-create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/balance/$id": {
      "filePath": "balance/$id.tsx"
    },
    "/nfts/create": {
      "filePath": "nfts/create.tsx"
    },
    "/nfts/my-nfts": {
      "filePath": "nfts/my-nfts.tsx"
    },
    "/currency-display/": {
      "filePath": "currency-display/index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    },
    "/receive/": {
      "filePath": "receive/index.tsx"
    },
    "/send/": {
      "filePath": "send/index.tsx"
    },
    "/token-create/": {
      "filePath": "token-create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
