export const defaultHash = '0x00';
export const STATUS = 'status';
export const BALANCE = 'balance';
export const HELP = 'help';
export const SEND = 'send';
export const ADDRESS = 'newaddress';
export const TOKENCREATE = 'tokencreate';
export const RPCHOST = 'http://127.0.0.1:9002/';
export const INSUFFICIENT = 'Insufficient funds..';